In [ ]:
#INSTALACIÓN DE LIBRERIAS
!pip install Torch==1.8.1
!pip install TorchVision

In [ ]:
#IMPORTS
import os
import shutil
import cv2

In [1]:
import os
import cv2

# Ruta de la carpeta que contiene las imágenes
ruta_carpeta = r'D:\Master\TFM\IDC_regular_ps50_idx5\00Prueba'

# Lista para almacenar los arrays de las imágenes
listado_arrays_imagenes = []
listado_arrays_etiquetas = []

# Recorrer las subcarpetas '0' y '1'
for subcarpeta in ['0', '1']:
    subcarpeta_ruta = os.path.join(ruta_carpeta, subcarpeta)

    # Para cada archivo en la subcarpeta
    for nombre_archivo in os.listdir(subcarpeta_ruta):
        # Comprobar si el archivo es una imagen (esto dependerá de las extensiones de archivo de tus imágenes)
        if nombre_archivo.endswith('.png'):
            # Construir la ruta completa del archivo
            ruta_archivo = os.path.join(subcarpeta_ruta, nombre_archivo)

            # Leer la imagen y convertirla a un array
            img = cv2.imread(ruta_archivo)
            # Añadir el array a la lista
            listado_arrays_imagenes.append(img)
            # Añadir la etiqueta correspondiente a la lista de etiquetas
            listado_arrays_etiquetas.append(int(subcarpeta))

# Ahora listado_arrays_imagenes es una lista de arrays de NumPy y listado_arrays_etiquetas contiene las etiquetas correspondientes

print(listado_arrays_imagenes[0])
print(listado_arrays_etiquetas[0])

FileNotFoundError: ignored

In [ ]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Asumimos que la lista 'listado_arrays_imagenes' existe y contiene las matrices de imágenes

# Verificar la forma de las matrices
shapes = set(img.shape for img in listado_arrays_imagenes)
if len(shapes) > 1:
    # Realizar operación de ajuste en las matrices para que tengan la misma forma
    max_shape = max(shapes, key=lambda x: np.prod(x))
    listado_arrays_imagenes = [np.pad(img, [(0, max_shape[0]-img.shape[0]),
                                           (0, max_shape[1]-img.shape[1]),
                                           (0, max_shape[2]-img.shape[2])],
                                      mode='constant', constant_values=0)
                               for img in listado_arrays_imagenes]

# Convertir la lista de imágenes en una matriz 4D
imagenes = np.stack(listado_arrays_imagenes)

# Obtener las dimensiones de las imágenes
num_imagenes, altura, anchura, canales = imagenes.shape

# Reshape para que las imágenes sean 2D
imagenes_2d = imagenes.reshape(num_imagenes, -1)

# Crear una instancia del escalador MinMaxScaler
scaler = MinMaxScaler()

# Aplicar el escalado a las imágenes
imagenes_escaladas = scaler.fit_transform(imagenes_2d)

# Reshape de nuevo a las dimensiones originales de las imágenes
imagenes_escaladas = imagenes_escaladas.reshape(num_imagenes, altura, anchura, canales)


In [ ]:
print(imagenes_escaladas[0])

[[[0.80632411 0.64313725 0.88492063]
  [0.76679842 0.60392157 0.87698413]
  [0.82608696 0.68627451 0.88095238]
  ...
  [0.92941176 0.87007874 0.94117647]
  [0.83921569 0.72440945 0.90980392]
  [0.92156863 0.83858268 0.95669291]]

 [[0.73517787 0.55686275 0.84920635]
  [0.69960474 0.50980392 0.86507937]
  [0.76679842 0.58823529 0.87698413]
  ...
  [0.80314961 0.66666667 0.89370079]
  [0.84313725 0.70588235 0.89803922]
  [0.90980392 0.83137255 0.9254902 ]]

 [[0.83333333 0.70355731 0.93227092]
  [0.77865613 0.61811024 0.8968254 ]
  [0.68379447 0.49212598 0.8531746 ]
  ...
  [0.85433071 0.72440945 0.86666667]
  [0.75686275 0.6        0.74509804]
  [0.81568627 0.64566929 0.89019608]]

 ...

 [[0.75889328 0.57086614 0.85433071]
  [0.72727273 0.50588235 0.84251969]
  [0.72332016 0.50787402 0.83464567]
  ...
  [0.7254902  0.47843137 0.76078431]
  [0.75686275 0.56078431 0.8       ]
  [0.7372549  0.50588235 0.74117647]]

 [[0.75590551 0.56692913 0.85490196]
  [0.72834646 0.50196078 0.83529412]


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.model_selection import ParameterGrid

# Convert lists to tensors
imagenes = torch.stack([torch.Tensor(img).permute(2, 0, 1) for img in imagenes])
etiquetas = torch.tensor(listado_arrays_etiquetas)

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(imagenes, etiquetas, test_size=0.2, random_state=42)

# Define custom dataset
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_dataset = CustomDataset(X_train, y_train)
test_dataset = CustomDataset(X_test, y_test)

# Define the model architecture
class Model(nn.Module):
    def __init__(self, num_neurons):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(3, num_neurons, 3)
        self.pool = nn.MaxPool2d(2)
        self.flatten = nn.Flatten()
        self.fc = nn.Linear(num_neurons*24*24, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.conv1(x)
        x = self.pool(x)
        x = self.flatten(x)
        x = self.fc(x)
        x = self.sigmoid(x)
        return x


# Define the function to create the model
# Define the function to create the model
def crear_modelo(num_neurons):
    model = Model(num_neurons)
    criterion = nn.BCELoss()
    optimizer = optim.Adam(model.parameters())
    return model, criterion, optimizer

# Define the grid of parameters
param_grid = {
    'num_neurons': [10, 20, 30, 40, 50],
}
# Perform grid search
best_accuracy = 0.0
best_params = None

for params in ParameterGrid(param_grid):
    model, criterion, optimizer = crear_modelo(params['num_neurons'])

    train_loader = DataLoader(train_dataset, batch_size=10, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=10, shuffle=False)

    for epoch in range(10):
        model.train()
        image_counter = 0
        for inputs, labels in train_loader:
            image_counter += inputs.size(0)
            print(f"Epoch: {epoch+1}, Processed images: {image_counter}")
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels.float().unsqueeze(1))
            loss.backward()
            optimizer.step()

        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for inputs, labels in test_loader:
                outputs = model(inputs)
                predicted = (outputs >= 0.5).squeeze().long()
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        accuracy = correct / total
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_params = params

print("Best Accuracy:", best_accuracy)
print("Best Parameters:", best_params)


Epoch: 1, Processed images: 10
Epoch: 1, Processed images: 20
Epoch: 1, Processed images: 30
Epoch: 1, Processed images: 40
Epoch: 1, Processed images: 50
Epoch: 1, Processed images: 60
Epoch: 1, Processed images: 70
Epoch: 1, Processed images: 80
Epoch: 1, Processed images: 90
Epoch: 1, Processed images: 100
Epoch: 1, Processed images: 110
Epoch: 1, Processed images: 120
Epoch: 1, Processed images: 130
Epoch: 1, Processed images: 140
Epoch: 1, Processed images: 150
Epoch: 1, Processed images: 160
Epoch: 1, Processed images: 170
Epoch: 1, Processed images: 180
Epoch: 1, Processed images: 190
Epoch: 1, Processed images: 200
Epoch: 1, Processed images: 210
Epoch: 1, Processed images: 220
Epoch: 1, Processed images: 230
Epoch: 1, Processed images: 240
Epoch: 1, Processed images: 250
Epoch: 1, Processed images: 260
Epoch: 1, Processed images: 270
Epoch: 1, Processed images: 280
Epoch: 1, Processed images: 290
Epoch: 1, Processed images: 300
Epoch: 1, Processed images: 310
Epoch: 1, Process

Epoch: 1, Processed images: 2700
Epoch: 1, Processed images: 2710
Epoch: 1, Processed images: 2720
Epoch: 1, Processed images: 2730
Epoch: 1, Processed images: 2740
Epoch: 1, Processed images: 2750
Epoch: 1, Processed images: 2760
Epoch: 1, Processed images: 2770
Epoch: 1, Processed images: 2780
Epoch: 1, Processed images: 2790
Epoch: 1, Processed images: 2800
Epoch: 1, Processed images: 2810
Epoch: 1, Processed images: 2820
Epoch: 1, Processed images: 2830
Epoch: 1, Processed images: 2840
Epoch: 1, Processed images: 2850
Epoch: 1, Processed images: 2860
Epoch: 1, Processed images: 2870
Epoch: 1, Processed images: 2880
Epoch: 1, Processed images: 2890
Epoch: 1, Processed images: 2900
Epoch: 1, Processed images: 2910
Epoch: 1, Processed images: 2920
Epoch: 1, Processed images: 2930
Epoch: 1, Processed images: 2940
Epoch: 1, Processed images: 2950
Epoch: 1, Processed images: 2960
Epoch: 1, Processed images: 2970
Epoch: 1, Processed images: 2980
Epoch: 1, Processed images: 2990
Epoch: 1, 

Epoch: 1, Processed images: 5270
Epoch: 1, Processed images: 5280
Epoch: 1, Processed images: 5290
Epoch: 1, Processed images: 5300
Epoch: 1, Processed images: 5310
Epoch: 1, Processed images: 5320
Epoch: 1, Processed images: 5330
Epoch: 1, Processed images: 5340
Epoch: 1, Processed images: 5350
Epoch: 1, Processed images: 5360
Epoch: 1, Processed images: 5370
Epoch: 1, Processed images: 5380
Epoch: 1, Processed images: 5390
Epoch: 1, Processed images: 5400
Epoch: 1, Processed images: 5410
Epoch: 1, Processed images: 5420
Epoch: 1, Processed images: 5430
Epoch: 1, Processed images: 5440
Epoch: 1, Processed images: 5450
Epoch: 1, Processed images: 5460
Epoch: 1, Processed images: 5470
Epoch: 1, Processed images: 5480
Epoch: 1, Processed images: 5490
Epoch: 1, Processed images: 5500
Epoch: 1, Processed images: 5510
Epoch: 1, Processed images: 5520
Epoch: 1, Processed images: 5530
Epoch: 1, Processed images: 5540
Epoch: 1, Processed images: 5550
Epoch: 1, Processed images: 5560
Epoch: 1, 

Epoch: 1, Processed images: 8010
Epoch: 1, Processed images: 8020
Epoch: 1, Processed images: 8030
Epoch: 1, Processed images: 8040
Epoch: 1, Processed images: 8050
Epoch: 1, Processed images: 8060
Epoch: 1, Processed images: 8070
Epoch: 1, Processed images: 8080
Epoch: 1, Processed images: 8090
Epoch: 1, Processed images: 8100
Epoch: 1, Processed images: 8110
Epoch: 1, Processed images: 8120
Epoch: 1, Processed images: 8130
Epoch: 1, Processed images: 8140
Epoch: 1, Processed images: 8150
Epoch: 1, Processed images: 8160
Epoch: 1, Processed images: 8170
Epoch: 1, Processed images: 8180
Epoch: 1, Processed images: 8190
Epoch: 1, Processed images: 8200
Epoch: 1, Processed images: 8210
Epoch: 1, Processed images: 8220
Epoch: 1, Processed images: 8230
Epoch: 1, Processed images: 8240
Epoch: 1, Processed images: 8250
Epoch: 1, Processed images: 8260
Epoch: 1, Processed images: 8270
Epoch: 1, Processed images: 8280
Epoch: 1, Processed images: 8290
Epoch: 1, Processed images: 8300
Epoch: 1, 

Epoch: 1, Processed images: 10770
Epoch: 1, Processed images: 10780
Epoch: 1, Processed images: 10790
Epoch: 1, Processed images: 10800
Epoch: 1, Processed images: 10810
Epoch: 1, Processed images: 10820
Epoch: 1, Processed images: 10830
Epoch: 1, Processed images: 10840
Epoch: 1, Processed images: 10850
Epoch: 1, Processed images: 10860
Epoch: 1, Processed images: 10870
Epoch: 1, Processed images: 10880
Epoch: 1, Processed images: 10890
Epoch: 1, Processed images: 10900
Epoch: 1, Processed images: 10910
Epoch: 1, Processed images: 10920
Epoch: 1, Processed images: 10930
Epoch: 1, Processed images: 10940
Epoch: 1, Processed images: 10950
Epoch: 1, Processed images: 10960
Epoch: 1, Processed images: 10970
Epoch: 1, Processed images: 10980
Epoch: 1, Processed images: 10990
Epoch: 1, Processed images: 11000
Epoch: 1, Processed images: 11010
Epoch: 1, Processed images: 11020
Epoch: 1, Processed images: 11030
Epoch: 1, Processed images: 11040
Epoch: 1, Processed images: 11050
Epoch: 1, Proc

Epoch: 1, Processed images: 13190
Epoch: 1, Processed images: 13200
Epoch: 1, Processed images: 13210
Epoch: 1, Processed images: 13220
Epoch: 1, Processed images: 13230
Epoch: 1, Processed images: 13240
Epoch: 1, Processed images: 13250
Epoch: 1, Processed images: 13260
Epoch: 1, Processed images: 13270
Epoch: 1, Processed images: 13280
Epoch: 1, Processed images: 13290
Epoch: 1, Processed images: 13300
Epoch: 1, Processed images: 13310
Epoch: 1, Processed images: 13320
Epoch: 1, Processed images: 13330
Epoch: 1, Processed images: 13340
Epoch: 1, Processed images: 13350
Epoch: 1, Processed images: 13360
Epoch: 1, Processed images: 13370
Epoch: 1, Processed images: 13380
Epoch: 1, Processed images: 13390
Epoch: 1, Processed images: 13400
Epoch: 1, Processed images: 13410
Epoch: 1, Processed images: 13420
Epoch: 1, Processed images: 13430
Epoch: 1, Processed images: 13440
Epoch: 1, Processed images: 13450
Epoch: 1, Processed images: 13460
Epoch: 1, Processed images: 13470
Epoch: 1, Proc

Epoch: 1, Processed images: 15820
Epoch: 1, Processed images: 15830
Epoch: 1, Processed images: 15840
Epoch: 1, Processed images: 15850
Epoch: 1, Processed images: 15860
Epoch: 1, Processed images: 15870
Epoch: 1, Processed images: 15880
Epoch: 1, Processed images: 15890
Epoch: 1, Processed images: 15900
Epoch: 1, Processed images: 15910
Epoch: 1, Processed images: 15920
Epoch: 1, Processed images: 15930
Epoch: 1, Processed images: 15940
Epoch: 1, Processed images: 15950
Epoch: 1, Processed images: 15960
Epoch: 1, Processed images: 15970
Epoch: 1, Processed images: 15980
Epoch: 1, Processed images: 15990
Epoch: 1, Processed images: 16000
Epoch: 1, Processed images: 16010
Epoch: 1, Processed images: 16020
Epoch: 1, Processed images: 16030
Epoch: 1, Processed images: 16040
Epoch: 1, Processed images: 16050
Epoch: 1, Processed images: 16060
Epoch: 1, Processed images: 16070
Epoch: 1, Processed images: 16080
Epoch: 1, Processed images: 16090
Epoch: 1, Processed images: 16100
Epoch: 1, Proc

Epoch: 1, Processed images: 18530
Epoch: 1, Processed images: 18540
Epoch: 1, Processed images: 18550
Epoch: 1, Processed images: 18560
Epoch: 1, Processed images: 18570
Epoch: 1, Processed images: 18580
Epoch: 1, Processed images: 18590
Epoch: 1, Processed images: 18600
Epoch: 1, Processed images: 18610
Epoch: 1, Processed images: 18620
Epoch: 1, Processed images: 18630
Epoch: 1, Processed images: 18640
Epoch: 1, Processed images: 18650
Epoch: 1, Processed images: 18660
Epoch: 1, Processed images: 18670
Epoch: 1, Processed images: 18680
Epoch: 1, Processed images: 18690
Epoch: 1, Processed images: 18700
Epoch: 1, Processed images: 18710
Epoch: 1, Processed images: 18720
Epoch: 1, Processed images: 18730
Epoch: 1, Processed images: 18740
Epoch: 1, Processed images: 18750
Epoch: 1, Processed images: 18760
Epoch: 1, Processed images: 18770
Epoch: 1, Processed images: 18780
Epoch: 1, Processed images: 18790
Epoch: 1, Processed images: 18800
Epoch: 1, Processed images: 18810
Epoch: 1, Proc

Epoch: 1, Processed images: 21120
Epoch: 1, Processed images: 21130
Epoch: 1, Processed images: 21140
Epoch: 1, Processed images: 21150
Epoch: 1, Processed images: 21160
Epoch: 1, Processed images: 21170
Epoch: 1, Processed images: 21180
Epoch: 1, Processed images: 21190
Epoch: 1, Processed images: 21200
Epoch: 1, Processed images: 21210
Epoch: 1, Processed images: 21220
Epoch: 1, Processed images: 21230
Epoch: 1, Processed images: 21240
Epoch: 1, Processed images: 21250
Epoch: 1, Processed images: 21260
Epoch: 1, Processed images: 21270
Epoch: 1, Processed images: 21280
Epoch: 1, Processed images: 21290
Epoch: 1, Processed images: 21300
Epoch: 1, Processed images: 21310
Epoch: 1, Processed images: 21320
Epoch: 1, Processed images: 21330
Epoch: 1, Processed images: 21340
Epoch: 1, Processed images: 21350
Epoch: 1, Processed images: 21360
Epoch: 1, Processed images: 21370
Epoch: 1, Processed images: 21380
Epoch: 1, Processed images: 21390
Epoch: 1, Processed images: 21400
Epoch: 1, Proc

Epoch: 1, Processed images: 23780
Epoch: 1, Processed images: 23790
Epoch: 1, Processed images: 23800
Epoch: 1, Processed images: 23810
Epoch: 1, Processed images: 23820
Epoch: 1, Processed images: 23830
Epoch: 1, Processed images: 23840
Epoch: 1, Processed images: 23850
Epoch: 1, Processed images: 23860
Epoch: 1, Processed images: 23870
Epoch: 1, Processed images: 23880
Epoch: 1, Processed images: 23890
Epoch: 1, Processed images: 23900
Epoch: 1, Processed images: 23910
Epoch: 1, Processed images: 23920
Epoch: 1, Processed images: 23930
Epoch: 1, Processed images: 23940
Epoch: 1, Processed images: 23950
Epoch: 1, Processed images: 23960
Epoch: 1, Processed images: 23970
Epoch: 1, Processed images: 23980
Epoch: 1, Processed images: 23990
Epoch: 1, Processed images: 24000
Epoch: 1, Processed images: 24010
Epoch: 1, Processed images: 24020
Epoch: 1, Processed images: 24030
Epoch: 1, Processed images: 24040
Epoch: 1, Processed images: 24050
Epoch: 1, Processed images: 24060
Epoch: 1, Proc

Epoch: 1, Processed images: 26500
Epoch: 1, Processed images: 26510
Epoch: 1, Processed images: 26520
Epoch: 1, Processed images: 26530
Epoch: 1, Processed images: 26540
Epoch: 1, Processed images: 26550
Epoch: 1, Processed images: 26560
Epoch: 1, Processed images: 26570
Epoch: 1, Processed images: 26580
Epoch: 1, Processed images: 26590
Epoch: 1, Processed images: 26600
Epoch: 1, Processed images: 26610
Epoch: 1, Processed images: 26620
Epoch: 1, Processed images: 26630
Epoch: 1, Processed images: 26640
Epoch: 1, Processed images: 26650
Epoch: 1, Processed images: 26660
Epoch: 1, Processed images: 26670
Epoch: 1, Processed images: 26680
Epoch: 1, Processed images: 26690
Epoch: 1, Processed images: 26700
Epoch: 1, Processed images: 26710
Epoch: 1, Processed images: 26720
Epoch: 1, Processed images: 26730
Epoch: 1, Processed images: 26740
Epoch: 1, Processed images: 26750
Epoch: 1, Processed images: 26760
Epoch: 1, Processed images: 26770
Epoch: 1, Processed images: 26780
Epoch: 1, Proc

Epoch: 1, Processed images: 29230
Epoch: 1, Processed images: 29240
Epoch: 1, Processed images: 29250
Epoch: 1, Processed images: 29260
Epoch: 1, Processed images: 29270
Epoch: 1, Processed images: 29280
Epoch: 1, Processed images: 29290
Epoch: 1, Processed images: 29300
Epoch: 1, Processed images: 29310
Epoch: 1, Processed images: 29320
Epoch: 1, Processed images: 29330
Epoch: 1, Processed images: 29340
Epoch: 1, Processed images: 29350
Epoch: 1, Processed images: 29360
Epoch: 1, Processed images: 29370
Epoch: 1, Processed images: 29380
Epoch: 1, Processed images: 29390
Epoch: 1, Processed images: 29400
Epoch: 1, Processed images: 29410
Epoch: 1, Processed images: 29420
Epoch: 1, Processed images: 29430
Epoch: 1, Processed images: 29440
Epoch: 1, Processed images: 29450
Epoch: 1, Processed images: 29460
Epoch: 1, Processed images: 29470
Epoch: 1, Processed images: 29480
Epoch: 1, Processed images: 29490
Epoch: 1, Processed images: 29500
Epoch: 1, Processed images: 29510
Epoch: 1, Proc

Epoch: 1, Processed images: 31850
Epoch: 1, Processed images: 31860
Epoch: 1, Processed images: 31870
Epoch: 1, Processed images: 31880
Epoch: 1, Processed images: 31890
Epoch: 1, Processed images: 31900
Epoch: 1, Processed images: 31910
Epoch: 1, Processed images: 31920
Epoch: 1, Processed images: 31930
Epoch: 1, Processed images: 31940
Epoch: 1, Processed images: 31950
Epoch: 1, Processed images: 31960
Epoch: 1, Processed images: 31970
Epoch: 1, Processed images: 31980
Epoch: 1, Processed images: 31990
Epoch: 1, Processed images: 32000
Epoch: 1, Processed images: 32010
Epoch: 1, Processed images: 32020
Epoch: 1, Processed images: 32030
Epoch: 1, Processed images: 32040
Epoch: 1, Processed images: 32050
Epoch: 1, Processed images: 32060
Epoch: 1, Processed images: 32070
Epoch: 1, Processed images: 32080
Epoch: 1, Processed images: 32090
Epoch: 1, Processed images: 32100
Epoch: 1, Processed images: 32110
Epoch: 1, Processed images: 32120
Epoch: 1, Processed images: 32130
Epoch: 1, Proc

Epoch: 1, Processed images: 34290
Epoch: 1, Processed images: 34300
Epoch: 1, Processed images: 34310
Epoch: 1, Processed images: 34320
Epoch: 1, Processed images: 34330
Epoch: 1, Processed images: 34340
Epoch: 1, Processed images: 34350
Epoch: 1, Processed images: 34360
Epoch: 1, Processed images: 34370
Epoch: 1, Processed images: 34380
Epoch: 1, Processed images: 34390
Epoch: 1, Processed images: 34400
Epoch: 1, Processed images: 34410
Epoch: 1, Processed images: 34420
Epoch: 1, Processed images: 34430
Epoch: 1, Processed images: 34440
Epoch: 1, Processed images: 34450
Epoch: 1, Processed images: 34460
Epoch: 1, Processed images: 34470
Epoch: 1, Processed images: 34480
Epoch: 1, Processed images: 34490
Epoch: 1, Processed images: 34500
Epoch: 1, Processed images: 34510
Epoch: 1, Processed images: 34520
Epoch: 1, Processed images: 34530
Epoch: 1, Processed images: 34540
Epoch: 1, Processed images: 34550
Epoch: 1, Processed images: 34560
Epoch: 1, Processed images: 34570
Epoch: 1, Proc

Epoch: 1, Processed images: 36930
Epoch: 1, Processed images: 36940
Epoch: 1, Processed images: 36950
Epoch: 1, Processed images: 36960
Epoch: 1, Processed images: 36970
Epoch: 1, Processed images: 36980
Epoch: 1, Processed images: 36990
Epoch: 1, Processed images: 37000
Epoch: 1, Processed images: 37010
Epoch: 1, Processed images: 37020
Epoch: 1, Processed images: 37030
Epoch: 1, Processed images: 37040
Epoch: 1, Processed images: 37050
Epoch: 1, Processed images: 37060
Epoch: 1, Processed images: 37070
Epoch: 1, Processed images: 37080
Epoch: 1, Processed images: 37090
Epoch: 1, Processed images: 37100
Epoch: 1, Processed images: 37110
Epoch: 1, Processed images: 37120
Epoch: 1, Processed images: 37130
Epoch: 1, Processed images: 37140
Epoch: 1, Processed images: 37150
Epoch: 1, Processed images: 37160
Epoch: 1, Processed images: 37170
Epoch: 1, Processed images: 37180
Epoch: 1, Processed images: 37190
Epoch: 1, Processed images: 37200
Epoch: 1, Processed images: 37210
Epoch: 1, Proc

Epoch: 2, Processed images: 1360
Epoch: 2, Processed images: 1370
Epoch: 2, Processed images: 1380
Epoch: 2, Processed images: 1390
Epoch: 2, Processed images: 1400
Epoch: 2, Processed images: 1410
Epoch: 2, Processed images: 1420
Epoch: 2, Processed images: 1430
Epoch: 2, Processed images: 1440
Epoch: 2, Processed images: 1450
Epoch: 2, Processed images: 1460
Epoch: 2, Processed images: 1470
Epoch: 2, Processed images: 1480
Epoch: 2, Processed images: 1490
Epoch: 2, Processed images: 1500
Epoch: 2, Processed images: 1510
Epoch: 2, Processed images: 1520
Epoch: 2, Processed images: 1530
Epoch: 2, Processed images: 1540
Epoch: 2, Processed images: 1550
Epoch: 2, Processed images: 1560
Epoch: 2, Processed images: 1570
Epoch: 2, Processed images: 1580
Epoch: 2, Processed images: 1590
Epoch: 2, Processed images: 1600
Epoch: 2, Processed images: 1610
Epoch: 2, Processed images: 1620
Epoch: 2, Processed images: 1630
Epoch: 2, Processed images: 1640
Epoch: 2, Processed images: 1650
Epoch: 2, 

Epoch: 2, Processed images: 4030
Epoch: 2, Processed images: 4040
Epoch: 2, Processed images: 4050
Epoch: 2, Processed images: 4060
Epoch: 2, Processed images: 4070
Epoch: 2, Processed images: 4080
Epoch: 2, Processed images: 4090
Epoch: 2, Processed images: 4100
Epoch: 2, Processed images: 4110
Epoch: 2, Processed images: 4120
Epoch: 2, Processed images: 4130
Epoch: 2, Processed images: 4140
Epoch: 2, Processed images: 4150
Epoch: 2, Processed images: 4160
Epoch: 2, Processed images: 4170
Epoch: 2, Processed images: 4180
Epoch: 2, Processed images: 4190
Epoch: 2, Processed images: 4200
Epoch: 2, Processed images: 4210
Epoch: 2, Processed images: 4220
Epoch: 2, Processed images: 4230
Epoch: 2, Processed images: 4240
Epoch: 2, Processed images: 4250
Epoch: 2, Processed images: 4260
Epoch: 2, Processed images: 4270
Epoch: 2, Processed images: 4280
Epoch: 2, Processed images: 4290
Epoch: 2, Processed images: 4300
Epoch: 2, Processed images: 4310
Epoch: 2, Processed images: 4320
Epoch: 2, 

Epoch: 2, Processed images: 6780
Epoch: 2, Processed images: 6790
Epoch: 2, Processed images: 6800
Epoch: 2, Processed images: 6810
Epoch: 2, Processed images: 6820
Epoch: 2, Processed images: 6830
Epoch: 2, Processed images: 6840
Epoch: 2, Processed images: 6850
Epoch: 2, Processed images: 6860
Epoch: 2, Processed images: 6870
Epoch: 2, Processed images: 6880
Epoch: 2, Processed images: 6890
Epoch: 2, Processed images: 6900
Epoch: 2, Processed images: 6910
Epoch: 2, Processed images: 6920
Epoch: 2, Processed images: 6930
Epoch: 2, Processed images: 6940
Epoch: 2, Processed images: 6950
Epoch: 2, Processed images: 6960
Epoch: 2, Processed images: 6970
Epoch: 2, Processed images: 6980
Epoch: 2, Processed images: 6990
Epoch: 2, Processed images: 7000
Epoch: 2, Processed images: 7010
Epoch: 2, Processed images: 7020
Epoch: 2, Processed images: 7030
Epoch: 2, Processed images: 7040
Epoch: 2, Processed images: 7050
Epoch: 2, Processed images: 7060
Epoch: 2, Processed images: 7070
Epoch: 2, 

Epoch: 2, Processed images: 9440
Epoch: 2, Processed images: 9450
Epoch: 2, Processed images: 9460
Epoch: 2, Processed images: 9470
Epoch: 2, Processed images: 9480
Epoch: 2, Processed images: 9490
Epoch: 2, Processed images: 9500
Epoch: 2, Processed images: 9510
Epoch: 2, Processed images: 9520
Epoch: 2, Processed images: 9530
Epoch: 2, Processed images: 9540
Epoch: 2, Processed images: 9550
Epoch: 2, Processed images: 9560
Epoch: 2, Processed images: 9570
Epoch: 2, Processed images: 9580
Epoch: 2, Processed images: 9590
Epoch: 2, Processed images: 9600
Epoch: 2, Processed images: 9610
Epoch: 2, Processed images: 9620
Epoch: 2, Processed images: 9630
Epoch: 2, Processed images: 9640
Epoch: 2, Processed images: 9650
Epoch: 2, Processed images: 9660
Epoch: 2, Processed images: 9670
Epoch: 2, Processed images: 9680
Epoch: 2, Processed images: 9690
Epoch: 2, Processed images: 9700
Epoch: 2, Processed images: 9710
Epoch: 2, Processed images: 9720
Epoch: 2, Processed images: 9730
Epoch: 2, 

Epoch: 2, Processed images: 12040
Epoch: 2, Processed images: 12050
Epoch: 2, Processed images: 12060
Epoch: 2, Processed images: 12070
Epoch: 2, Processed images: 12080
Epoch: 2, Processed images: 12090
Epoch: 2, Processed images: 12100
Epoch: 2, Processed images: 12110
Epoch: 2, Processed images: 12120
Epoch: 2, Processed images: 12130
Epoch: 2, Processed images: 12140
Epoch: 2, Processed images: 12150
Epoch: 2, Processed images: 12160
Epoch: 2, Processed images: 12170
Epoch: 2, Processed images: 12180
Epoch: 2, Processed images: 12190
Epoch: 2, Processed images: 12200
Epoch: 2, Processed images: 12210
Epoch: 2, Processed images: 12220
Epoch: 2, Processed images: 12230
Epoch: 2, Processed images: 12240
Epoch: 2, Processed images: 12250
Epoch: 2, Processed images: 12260
Epoch: 2, Processed images: 12270
Epoch: 2, Processed images: 12280
Epoch: 2, Processed images: 12290
Epoch: 2, Processed images: 12300
Epoch: 2, Processed images: 12310
Epoch: 2, Processed images: 12320
Epoch: 2, Proc

Epoch: 2, Processed images: 14690
Epoch: 2, Processed images: 14700
Epoch: 2, Processed images: 14710
Epoch: 2, Processed images: 14720
Epoch: 2, Processed images: 14730
Epoch: 2, Processed images: 14740
Epoch: 2, Processed images: 14750
Epoch: 2, Processed images: 14760
Epoch: 2, Processed images: 14770
Epoch: 2, Processed images: 14780
Epoch: 2, Processed images: 14790
Epoch: 2, Processed images: 14800
Epoch: 2, Processed images: 14810
Epoch: 2, Processed images: 14820
Epoch: 2, Processed images: 14830
Epoch: 2, Processed images: 14840
Epoch: 2, Processed images: 14850
Epoch: 2, Processed images: 14860
Epoch: 2, Processed images: 14870
Epoch: 2, Processed images: 14880
Epoch: 2, Processed images: 14890
Epoch: 2, Processed images: 14900
Epoch: 2, Processed images: 14910
Epoch: 2, Processed images: 14920
Epoch: 2, Processed images: 14930
Epoch: 2, Processed images: 14940
Epoch: 2, Processed images: 14950
Epoch: 2, Processed images: 14960
Epoch: 2, Processed images: 14970
Epoch: 2, Proc

Epoch: 2, Processed images: 17200
Epoch: 2, Processed images: 17210
Epoch: 2, Processed images: 17220
Epoch: 2, Processed images: 17230
Epoch: 2, Processed images: 17240
Epoch: 2, Processed images: 17250
Epoch: 2, Processed images: 17260
Epoch: 2, Processed images: 17270
Epoch: 2, Processed images: 17280
Epoch: 2, Processed images: 17290
Epoch: 2, Processed images: 17300
Epoch: 2, Processed images: 17310
Epoch: 2, Processed images: 17320
Epoch: 2, Processed images: 17330
Epoch: 2, Processed images: 17340
Epoch: 2, Processed images: 17350
Epoch: 2, Processed images: 17360
Epoch: 2, Processed images: 17370
Epoch: 2, Processed images: 17380
Epoch: 2, Processed images: 17390
Epoch: 2, Processed images: 17400
Epoch: 2, Processed images: 17410
Epoch: 2, Processed images: 17420
Epoch: 2, Processed images: 17430
Epoch: 2, Processed images: 17440
Epoch: 2, Processed images: 17450
Epoch: 2, Processed images: 17460
Epoch: 2, Processed images: 17470
Epoch: 2, Processed images: 17480
Epoch: 2, Proc

Epoch: 2, Processed images: 19820
Epoch: 2, Processed images: 19830
Epoch: 2, Processed images: 19840
Epoch: 2, Processed images: 19850
Epoch: 2, Processed images: 19860
Epoch: 2, Processed images: 19870
Epoch: 2, Processed images: 19880
Epoch: 2, Processed images: 19890
Epoch: 2, Processed images: 19900
Epoch: 2, Processed images: 19910
Epoch: 2, Processed images: 19920
Epoch: 2, Processed images: 19930
Epoch: 2, Processed images: 19940
Epoch: 2, Processed images: 19950
Epoch: 2, Processed images: 19960
Epoch: 2, Processed images: 19970
Epoch: 2, Processed images: 19980
Epoch: 2, Processed images: 19990
Epoch: 2, Processed images: 20000
Epoch: 2, Processed images: 20010
Epoch: 2, Processed images: 20020
Epoch: 2, Processed images: 20030
Epoch: 2, Processed images: 20040
Epoch: 2, Processed images: 20050
Epoch: 2, Processed images: 20060
Epoch: 2, Processed images: 20070
Epoch: 2, Processed images: 20080
Epoch: 2, Processed images: 20090
Epoch: 2, Processed images: 20100
Epoch: 2, Proc

Epoch: 2, Processed images: 22430
Epoch: 2, Processed images: 22440
Epoch: 2, Processed images: 22450
Epoch: 2, Processed images: 22460
Epoch: 2, Processed images: 22470
Epoch: 2, Processed images: 22480
Epoch: 2, Processed images: 22490
Epoch: 2, Processed images: 22500
Epoch: 2, Processed images: 22510
Epoch: 2, Processed images: 22520
Epoch: 2, Processed images: 22530
Epoch: 2, Processed images: 22540
Epoch: 2, Processed images: 22550
Epoch: 2, Processed images: 22560
Epoch: 2, Processed images: 22570
Epoch: 2, Processed images: 22580
Epoch: 2, Processed images: 22590
Epoch: 2, Processed images: 22600
Epoch: 2, Processed images: 22610
Epoch: 2, Processed images: 22620
Epoch: 2, Processed images: 22630
Epoch: 2, Processed images: 22640
Epoch: 2, Processed images: 22650
Epoch: 2, Processed images: 22660
Epoch: 2, Processed images: 22670
Epoch: 2, Processed images: 22680
Epoch: 2, Processed images: 22690
Epoch: 2, Processed images: 22700
Epoch: 2, Processed images: 22710
Epoch: 2, Proc

Epoch: 2, Processed images: 24890
Epoch: 2, Processed images: 24900
Epoch: 2, Processed images: 24910
Epoch: 2, Processed images: 24920
Epoch: 2, Processed images: 24930
Epoch: 2, Processed images: 24940
Epoch: 2, Processed images: 24950
Epoch: 2, Processed images: 24960
Epoch: 2, Processed images: 24970
Epoch: 2, Processed images: 24980
Epoch: 2, Processed images: 24990
Epoch: 2, Processed images: 25000
Epoch: 2, Processed images: 25010
Epoch: 2, Processed images: 25020
Epoch: 2, Processed images: 25030
Epoch: 2, Processed images: 25040
Epoch: 2, Processed images: 25050
Epoch: 2, Processed images: 25060
Epoch: 2, Processed images: 25070
Epoch: 2, Processed images: 25080
Epoch: 2, Processed images: 25090
Epoch: 2, Processed images: 25100
Epoch: 2, Processed images: 25110
Epoch: 2, Processed images: 25120
Epoch: 2, Processed images: 25130
Epoch: 2, Processed images: 25140
Epoch: 2, Processed images: 25150
Epoch: 2, Processed images: 25160
Epoch: 2, Processed images: 25170
Epoch: 2, Proc

Epoch: 2, Processed images: 27490
Epoch: 2, Processed images: 27500
Epoch: 2, Processed images: 27510
Epoch: 2, Processed images: 27520
Epoch: 2, Processed images: 27530
Epoch: 2, Processed images: 27540
Epoch: 2, Processed images: 27550
Epoch: 2, Processed images: 27560
Epoch: 2, Processed images: 27570
Epoch: 2, Processed images: 27580
Epoch: 2, Processed images: 27590
Epoch: 2, Processed images: 27600
Epoch: 2, Processed images: 27610
Epoch: 2, Processed images: 27620
Epoch: 2, Processed images: 27630
Epoch: 2, Processed images: 27640
Epoch: 2, Processed images: 27650
Epoch: 2, Processed images: 27660
Epoch: 2, Processed images: 27670
Epoch: 2, Processed images: 27680
Epoch: 2, Processed images: 27690
Epoch: 2, Processed images: 27700
Epoch: 2, Processed images: 27710
Epoch: 2, Processed images: 27720
Epoch: 2, Processed images: 27730
Epoch: 2, Processed images: 27740
Epoch: 2, Processed images: 27750
Epoch: 2, Processed images: 27760
Epoch: 2, Processed images: 27770
Epoch: 2, Proc

Epoch: 2, Processed images: 30170
Epoch: 2, Processed images: 30180
Epoch: 2, Processed images: 30190
Epoch: 2, Processed images: 30200
Epoch: 2, Processed images: 30210
Epoch: 2, Processed images: 30220
Epoch: 2, Processed images: 30230
Epoch: 2, Processed images: 30240
Epoch: 2, Processed images: 30250
Epoch: 2, Processed images: 30260
Epoch: 2, Processed images: 30270
Epoch: 2, Processed images: 30280
Epoch: 2, Processed images: 30290
Epoch: 2, Processed images: 30300
Epoch: 2, Processed images: 30310
Epoch: 2, Processed images: 30320
Epoch: 2, Processed images: 30330
Epoch: 2, Processed images: 30340
Epoch: 2, Processed images: 30350
Epoch: 2, Processed images: 30360
Epoch: 2, Processed images: 30370
Epoch: 2, Processed images: 30380
Epoch: 2, Processed images: 30390
Epoch: 2, Processed images: 30400
Epoch: 2, Processed images: 30410
Epoch: 2, Processed images: 30420
Epoch: 2, Processed images: 30430
Epoch: 2, Processed images: 30440
Epoch: 2, Processed images: 30450
Epoch: 2, Proc

Epoch: 2, Processed images: 32900
Epoch: 2, Processed images: 32910
Epoch: 2, Processed images: 32920
Epoch: 2, Processed images: 32930
Epoch: 2, Processed images: 32940
Epoch: 2, Processed images: 32950
Epoch: 2, Processed images: 32960
Epoch: 2, Processed images: 32970
Epoch: 2, Processed images: 32980
Epoch: 2, Processed images: 32990
Epoch: 2, Processed images: 33000
Epoch: 2, Processed images: 33010
Epoch: 2, Processed images: 33020
Epoch: 2, Processed images: 33030
Epoch: 2, Processed images: 33040
Epoch: 2, Processed images: 33050
Epoch: 2, Processed images: 33060
Epoch: 2, Processed images: 33070
Epoch: 2, Processed images: 33080
Epoch: 2, Processed images: 33090
Epoch: 2, Processed images: 33100
Epoch: 2, Processed images: 33110
Epoch: 2, Processed images: 33120
Epoch: 2, Processed images: 33130
Epoch: 2, Processed images: 33140
Epoch: 2, Processed images: 33150
Epoch: 2, Processed images: 33160
Epoch: 2, Processed images: 33170
Epoch: 2, Processed images: 33180
Epoch: 2, Proc

Epoch: 2, Processed images: 35540
Epoch: 2, Processed images: 35550
Epoch: 2, Processed images: 35560
Epoch: 2, Processed images: 35570
Epoch: 2, Processed images: 35580
Epoch: 2, Processed images: 35590
Epoch: 2, Processed images: 35600
Epoch: 2, Processed images: 35610
Epoch: 2, Processed images: 35620
Epoch: 2, Processed images: 35630
Epoch: 2, Processed images: 35640
Epoch: 2, Processed images: 35650
Epoch: 2, Processed images: 35660
Epoch: 2, Processed images: 35670
Epoch: 2, Processed images: 35680
Epoch: 2, Processed images: 35690
Epoch: 2, Processed images: 35700
Epoch: 2, Processed images: 35710
Epoch: 2, Processed images: 35720
Epoch: 2, Processed images: 35730
Epoch: 2, Processed images: 35740
Epoch: 2, Processed images: 35750
Epoch: 2, Processed images: 35760
Epoch: 2, Processed images: 35770
Epoch: 2, Processed images: 35780
Epoch: 2, Processed images: 35790
Epoch: 2, Processed images: 35800
Epoch: 2, Processed images: 35810
Epoch: 2, Processed images: 35820
Epoch: 2, Proc

Epoch: 3, Processed images: 10
Epoch: 3, Processed images: 20
Epoch: 3, Processed images: 30
Epoch: 3, Processed images: 40
Epoch: 3, Processed images: 50
Epoch: 3, Processed images: 60
Epoch: 3, Processed images: 70
Epoch: 3, Processed images: 80
Epoch: 3, Processed images: 90
Epoch: 3, Processed images: 100
Epoch: 3, Processed images: 110
Epoch: 3, Processed images: 120
Epoch: 3, Processed images: 130
Epoch: 3, Processed images: 140
Epoch: 3, Processed images: 150
Epoch: 3, Processed images: 160
Epoch: 3, Processed images: 170
Epoch: 3, Processed images: 180
Epoch: 3, Processed images: 190
Epoch: 3, Processed images: 200
Epoch: 3, Processed images: 210
Epoch: 3, Processed images: 220
Epoch: 3, Processed images: 230
Epoch: 3, Processed images: 240
Epoch: 3, Processed images: 250
Epoch: 3, Processed images: 260
Epoch: 3, Processed images: 270
Epoch: 3, Processed images: 280
Epoch: 3, Processed images: 290
Epoch: 3, Processed images: 300
Epoch: 3, Processed images: 310
Epoch: 3, Process

Epoch: 3, Processed images: 2760
Epoch: 3, Processed images: 2770
Epoch: 3, Processed images: 2780
Epoch: 3, Processed images: 2790
Epoch: 3, Processed images: 2800
Epoch: 3, Processed images: 2810
Epoch: 3, Processed images: 2820
Epoch: 3, Processed images: 2830
Epoch: 3, Processed images: 2840
Epoch: 3, Processed images: 2850
Epoch: 3, Processed images: 2860
Epoch: 3, Processed images: 2870
Epoch: 3, Processed images: 2880
Epoch: 3, Processed images: 2890
Epoch: 3, Processed images: 2900
Epoch: 3, Processed images: 2910
Epoch: 3, Processed images: 2920
Epoch: 3, Processed images: 2930
Epoch: 3, Processed images: 2940
Epoch: 3, Processed images: 2950
Epoch: 3, Processed images: 2960
Epoch: 3, Processed images: 2970
Epoch: 3, Processed images: 2980
Epoch: 3, Processed images: 2990
Epoch: 3, Processed images: 3000
Epoch: 3, Processed images: 3010
Epoch: 3, Processed images: 3020
Epoch: 3, Processed images: 3030
Epoch: 3, Processed images: 3040
Epoch: 3, Processed images: 3050
Epoch: 3, 

Epoch: 3, Processed images: 5500
Epoch: 3, Processed images: 5510
Epoch: 3, Processed images: 5520
Epoch: 3, Processed images: 5530
Epoch: 3, Processed images: 5540
Epoch: 3, Processed images: 5550
Epoch: 3, Processed images: 5560
Epoch: 3, Processed images: 5570
Epoch: 3, Processed images: 5580
Epoch: 3, Processed images: 5590
Epoch: 3, Processed images: 5600
Epoch: 3, Processed images: 5610
Epoch: 3, Processed images: 5620
Epoch: 3, Processed images: 5630
Epoch: 3, Processed images: 5640
Epoch: 3, Processed images: 5650
Epoch: 3, Processed images: 5660
Epoch: 3, Processed images: 5670
Epoch: 3, Processed images: 5680
Epoch: 3, Processed images: 5690
Epoch: 3, Processed images: 5700
Epoch: 3, Processed images: 5710
Epoch: 3, Processed images: 5720
Epoch: 3, Processed images: 5730
Epoch: 3, Processed images: 5740
Epoch: 3, Processed images: 5750
Epoch: 3, Processed images: 5760
Epoch: 3, Processed images: 5770
Epoch: 3, Processed images: 5780
Epoch: 3, Processed images: 5790
Epoch: 3, 

Epoch: 3, Processed images: 8300
Epoch: 3, Processed images: 8310
Epoch: 3, Processed images: 8320
Epoch: 3, Processed images: 8330
Epoch: 3, Processed images: 8340
Epoch: 3, Processed images: 8350
Epoch: 3, Processed images: 8360
Epoch: 3, Processed images: 8370
Epoch: 3, Processed images: 8380
Epoch: 3, Processed images: 8390
Epoch: 3, Processed images: 8400
Epoch: 3, Processed images: 8410
Epoch: 3, Processed images: 8420
Epoch: 3, Processed images: 8430
Epoch: 3, Processed images: 8440
Epoch: 3, Processed images: 8450
Epoch: 3, Processed images: 8460
Epoch: 3, Processed images: 8470
Epoch: 3, Processed images: 8480
Epoch: 3, Processed images: 8490
Epoch: 3, Processed images: 8500
Epoch: 3, Processed images: 8510
Epoch: 3, Processed images: 8520
Epoch: 3, Processed images: 8530
Epoch: 3, Processed images: 8540
Epoch: 3, Processed images: 8550
Epoch: 3, Processed images: 8560
Epoch: 3, Processed images: 8570
Epoch: 3, Processed images: 8580
Epoch: 3, Processed images: 8590
Epoch: 3, 

Epoch: 3, Processed images: 10810
Epoch: 3, Processed images: 10820
Epoch: 3, Processed images: 10830
Epoch: 3, Processed images: 10840
Epoch: 3, Processed images: 10850
Epoch: 3, Processed images: 10860
Epoch: 3, Processed images: 10870
Epoch: 3, Processed images: 10880
Epoch: 3, Processed images: 10890
Epoch: 3, Processed images: 10900
Epoch: 3, Processed images: 10910
Epoch: 3, Processed images: 10920
Epoch: 3, Processed images: 10930
Epoch: 3, Processed images: 10940
Epoch: 3, Processed images: 10950
Epoch: 3, Processed images: 10960
Epoch: 3, Processed images: 10970
Epoch: 3, Processed images: 10980
Epoch: 3, Processed images: 10990
Epoch: 3, Processed images: 11000
Epoch: 3, Processed images: 11010
Epoch: 3, Processed images: 11020
Epoch: 3, Processed images: 11030
Epoch: 3, Processed images: 11040
Epoch: 3, Processed images: 11050
Epoch: 3, Processed images: 11060
Epoch: 3, Processed images: 11070
Epoch: 3, Processed images: 11080
Epoch: 3, Processed images: 11090
Epoch: 3, Proc

Epoch: 3, Processed images: 13500
Epoch: 3, Processed images: 13510
Epoch: 3, Processed images: 13520
Epoch: 3, Processed images: 13530
Epoch: 3, Processed images: 13540
Epoch: 3, Processed images: 13550
Epoch: 3, Processed images: 13560
Epoch: 3, Processed images: 13570
Epoch: 3, Processed images: 13580
Epoch: 3, Processed images: 13590
Epoch: 3, Processed images: 13600
Epoch: 3, Processed images: 13610
Epoch: 3, Processed images: 13620
Epoch: 3, Processed images: 13630
Epoch: 3, Processed images: 13640
Epoch: 3, Processed images: 13650
Epoch: 3, Processed images: 13660
Epoch: 3, Processed images: 13670
Epoch: 3, Processed images: 13680
Epoch: 3, Processed images: 13690
Epoch: 3, Processed images: 13700
Epoch: 3, Processed images: 13710
Epoch: 3, Processed images: 13720
Epoch: 3, Processed images: 13730
Epoch: 3, Processed images: 13740
Epoch: 3, Processed images: 13750
Epoch: 3, Processed images: 13760
Epoch: 3, Processed images: 13770
Epoch: 3, Processed images: 13780
Epoch: 3, Proc

Epoch: 3, Processed images: 15930
Epoch: 3, Processed images: 15940
Epoch: 3, Processed images: 15950
Epoch: 3, Processed images: 15960
Epoch: 3, Processed images: 15970
Epoch: 3, Processed images: 15980
Epoch: 3, Processed images: 15990
Epoch: 3, Processed images: 16000
Epoch: 3, Processed images: 16010
Epoch: 3, Processed images: 16020
Epoch: 3, Processed images: 16030
Epoch: 3, Processed images: 16040
Epoch: 3, Processed images: 16050
Epoch: 3, Processed images: 16060
Epoch: 3, Processed images: 16070
Epoch: 3, Processed images: 16080
Epoch: 3, Processed images: 16090
Epoch: 3, Processed images: 16100
Epoch: 3, Processed images: 16110
Epoch: 3, Processed images: 16120
Epoch: 3, Processed images: 16130
Epoch: 3, Processed images: 16140
Epoch: 3, Processed images: 16150
Epoch: 3, Processed images: 16160
Epoch: 3, Processed images: 16170
Epoch: 3, Processed images: 16180
Epoch: 3, Processed images: 16190
Epoch: 3, Processed images: 16200
Epoch: 3, Processed images: 16210
Epoch: 3, Proc

Epoch: 3, Processed images: 18460
Epoch: 3, Processed images: 18470
Epoch: 3, Processed images: 18480
Epoch: 3, Processed images: 18490
Epoch: 3, Processed images: 18500
Epoch: 3, Processed images: 18510
Epoch: 3, Processed images: 18520
Epoch: 3, Processed images: 18530
Epoch: 3, Processed images: 18540
Epoch: 3, Processed images: 18550
Epoch: 3, Processed images: 18560
Epoch: 3, Processed images: 18570
Epoch: 3, Processed images: 18580
Epoch: 3, Processed images: 18590
Epoch: 3, Processed images: 18600
Epoch: 3, Processed images: 18610
Epoch: 3, Processed images: 18620
Epoch: 3, Processed images: 18630
Epoch: 3, Processed images: 18640
Epoch: 3, Processed images: 18650
Epoch: 3, Processed images: 18660
Epoch: 3, Processed images: 18670
Epoch: 3, Processed images: 18680
Epoch: 3, Processed images: 18690
Epoch: 3, Processed images: 18700
Epoch: 3, Processed images: 18710
Epoch: 3, Processed images: 18720
Epoch: 3, Processed images: 18730
Epoch: 3, Processed images: 18740
Epoch: 3, Proc

Epoch: 3, Processed images: 20940
Epoch: 3, Processed images: 20950
Epoch: 3, Processed images: 20960
Epoch: 3, Processed images: 20970
Epoch: 3, Processed images: 20980
Epoch: 3, Processed images: 20990
Epoch: 3, Processed images: 21000
Epoch: 3, Processed images: 21010
Epoch: 3, Processed images: 21020
Epoch: 3, Processed images: 21030
Epoch: 3, Processed images: 21040
Epoch: 3, Processed images: 21050
Epoch: 3, Processed images: 21060
Epoch: 3, Processed images: 21070
Epoch: 3, Processed images: 21080
Epoch: 3, Processed images: 21090
Epoch: 3, Processed images: 21100
Epoch: 3, Processed images: 21110
Epoch: 3, Processed images: 21120
Epoch: 3, Processed images: 21130
Epoch: 3, Processed images: 21140
Epoch: 3, Processed images: 21150
Epoch: 3, Processed images: 21160
Epoch: 3, Processed images: 21170
Epoch: 3, Processed images: 21180
Epoch: 3, Processed images: 21190
Epoch: 3, Processed images: 21200
Epoch: 3, Processed images: 21210
Epoch: 3, Processed images: 21220
Epoch: 3, Proc

Epoch: 3, Processed images: 23540
Epoch: 3, Processed images: 23550
Epoch: 3, Processed images: 23560
Epoch: 3, Processed images: 23570
Epoch: 3, Processed images: 23580
Epoch: 3, Processed images: 23590
Epoch: 3, Processed images: 23600
Epoch: 3, Processed images: 23610
Epoch: 3, Processed images: 23620
Epoch: 3, Processed images: 23630
Epoch: 3, Processed images: 23640
Epoch: 3, Processed images: 23650
Epoch: 3, Processed images: 23660
Epoch: 3, Processed images: 23670
Epoch: 3, Processed images: 23680
Epoch: 3, Processed images: 23690
Epoch: 3, Processed images: 23700
Epoch: 3, Processed images: 23710
Epoch: 3, Processed images: 23720
Epoch: 3, Processed images: 23730
Epoch: 3, Processed images: 23740
Epoch: 3, Processed images: 23750
Epoch: 3, Processed images: 23760
Epoch: 3, Processed images: 23770
Epoch: 3, Processed images: 23780
Epoch: 3, Processed images: 23790
Epoch: 3, Processed images: 23800
Epoch: 3, Processed images: 23810
Epoch: 3, Processed images: 23820
Epoch: 3, Proc

Epoch: 3, Processed images: 26120
Epoch: 3, Processed images: 26130
Epoch: 3, Processed images: 26140
Epoch: 3, Processed images: 26150
Epoch: 3, Processed images: 26160
Epoch: 3, Processed images: 26170
Epoch: 3, Processed images: 26180
Epoch: 3, Processed images: 26190
Epoch: 3, Processed images: 26200
Epoch: 3, Processed images: 26210
Epoch: 3, Processed images: 26220
Epoch: 3, Processed images: 26230
Epoch: 3, Processed images: 26240
Epoch: 3, Processed images: 26250
Epoch: 3, Processed images: 26260
Epoch: 3, Processed images: 26270
Epoch: 3, Processed images: 26280
Epoch: 3, Processed images: 26290
Epoch: 3, Processed images: 26300
Epoch: 3, Processed images: 26310
Epoch: 3, Processed images: 26320
Epoch: 3, Processed images: 26330
Epoch: 3, Processed images: 26340
Epoch: 3, Processed images: 26350
Epoch: 3, Processed images: 26360
Epoch: 3, Processed images: 26370
Epoch: 3, Processed images: 26380
Epoch: 3, Processed images: 26390
Epoch: 3, Processed images: 26400
Epoch: 3, Proc

Epoch: 3, Processed images: 28790
Epoch: 3, Processed images: 28800
Epoch: 3, Processed images: 28810
Epoch: 3, Processed images: 28820
Epoch: 3, Processed images: 28830
Epoch: 3, Processed images: 28840
Epoch: 3, Processed images: 28850
Epoch: 3, Processed images: 28860
Epoch: 3, Processed images: 28870
Epoch: 3, Processed images: 28880
Epoch: 3, Processed images: 28890
Epoch: 3, Processed images: 28900
Epoch: 3, Processed images: 28910
Epoch: 3, Processed images: 28920
Epoch: 3, Processed images: 28930
Epoch: 3, Processed images: 28940
Epoch: 3, Processed images: 28950
Epoch: 3, Processed images: 28960
Epoch: 3, Processed images: 28970
Epoch: 3, Processed images: 28980
Epoch: 3, Processed images: 28990
Epoch: 3, Processed images: 29000
Epoch: 3, Processed images: 29010
Epoch: 3, Processed images: 29020
Epoch: 3, Processed images: 29030
Epoch: 3, Processed images: 29040
Epoch: 3, Processed images: 29050
Epoch: 3, Processed images: 29060
Epoch: 3, Processed images: 29070
Epoch: 3, Proc

Epoch: 3, Processed images: 31290
Epoch: 3, Processed images: 31300
Epoch: 3, Processed images: 31310
Epoch: 3, Processed images: 31320
Epoch: 3, Processed images: 31330
Epoch: 3, Processed images: 31340
Epoch: 3, Processed images: 31350
Epoch: 3, Processed images: 31360
Epoch: 3, Processed images: 31370
Epoch: 3, Processed images: 31380
Epoch: 3, Processed images: 31390
Epoch: 3, Processed images: 31400
Epoch: 3, Processed images: 31410
Epoch: 3, Processed images: 31420
Epoch: 3, Processed images: 31430
Epoch: 3, Processed images: 31440
Epoch: 3, Processed images: 31450
Epoch: 3, Processed images: 31460
Epoch: 3, Processed images: 31470
Epoch: 3, Processed images: 31480
Epoch: 3, Processed images: 31490
Epoch: 3, Processed images: 31500
Epoch: 3, Processed images: 31510
Epoch: 3, Processed images: 31520
Epoch: 3, Processed images: 31530
Epoch: 3, Processed images: 31540
Epoch: 3, Processed images: 31550
Epoch: 3, Processed images: 31560
Epoch: 3, Processed images: 31570
Epoch: 3, Proc

Epoch: 3, Processed images: 33890
Epoch: 3, Processed images: 33900
Epoch: 3, Processed images: 33910
Epoch: 3, Processed images: 33920
Epoch: 3, Processed images: 33930
Epoch: 3, Processed images: 33940
Epoch: 3, Processed images: 33950
Epoch: 3, Processed images: 33960
Epoch: 3, Processed images: 33970
Epoch: 3, Processed images: 33980
Epoch: 3, Processed images: 33990
Epoch: 3, Processed images: 34000
Epoch: 3, Processed images: 34010
Epoch: 3, Processed images: 34020
Epoch: 3, Processed images: 34030
Epoch: 3, Processed images: 34040
Epoch: 3, Processed images: 34050
Epoch: 3, Processed images: 34060
Epoch: 3, Processed images: 34070
Epoch: 3, Processed images: 34080
Epoch: 3, Processed images: 34090
Epoch: 3, Processed images: 34100
Epoch: 3, Processed images: 34110
Epoch: 3, Processed images: 34120
Epoch: 3, Processed images: 34130
Epoch: 3, Processed images: 34140
Epoch: 3, Processed images: 34150
Epoch: 3, Processed images: 34160
Epoch: 3, Processed images: 34170
Epoch: 3, Proc

Epoch: 3, Processed images: 36360
Epoch: 3, Processed images: 36370
Epoch: 3, Processed images: 36380
Epoch: 3, Processed images: 36390
Epoch: 3, Processed images: 36400
Epoch: 3, Processed images: 36410
Epoch: 3, Processed images: 36420
Epoch: 3, Processed images: 36430
Epoch: 3, Processed images: 36440
Epoch: 3, Processed images: 36450
Epoch: 3, Processed images: 36460
Epoch: 3, Processed images: 36470
Epoch: 3, Processed images: 36480
Epoch: 3, Processed images: 36490
Epoch: 3, Processed images: 36500
Epoch: 3, Processed images: 36510
Epoch: 3, Processed images: 36520
Epoch: 3, Processed images: 36530
Epoch: 3, Processed images: 36540
Epoch: 3, Processed images: 36550
Epoch: 3, Processed images: 36560
Epoch: 3, Processed images: 36570
Epoch: 3, Processed images: 36580
Epoch: 3, Processed images: 36590
Epoch: 3, Processed images: 36600
Epoch: 3, Processed images: 36610
Epoch: 3, Processed images: 36620
Epoch: 3, Processed images: 36630
Epoch: 3, Processed images: 36640
Epoch: 3, Proc

Epoch: 4, Processed images: 590
Epoch: 4, Processed images: 600
Epoch: 4, Processed images: 610
Epoch: 4, Processed images: 620
Epoch: 4, Processed images: 630
Epoch: 4, Processed images: 640
Epoch: 4, Processed images: 650
Epoch: 4, Processed images: 660
Epoch: 4, Processed images: 670
Epoch: 4, Processed images: 680
Epoch: 4, Processed images: 690
Epoch: 4, Processed images: 700
Epoch: 4, Processed images: 710
Epoch: 4, Processed images: 720
Epoch: 4, Processed images: 730
Epoch: 4, Processed images: 740
Epoch: 4, Processed images: 750
Epoch: 4, Processed images: 760
Epoch: 4, Processed images: 770
Epoch: 4, Processed images: 780
Epoch: 4, Processed images: 790
Epoch: 4, Processed images: 800
Epoch: 4, Processed images: 810
Epoch: 4, Processed images: 820
Epoch: 4, Processed images: 830
Epoch: 4, Processed images: 840
Epoch: 4, Processed images: 850
Epoch: 4, Processed images: 860
Epoch: 4, Processed images: 870
Epoch: 4, Processed images: 880
Epoch: 4, Processed images: 890
Epoch: 4

Epoch: 4, Processed images: 3220
Epoch: 4, Processed images: 3230
Epoch: 4, Processed images: 3240
Epoch: 4, Processed images: 3250
Epoch: 4, Processed images: 3260
Epoch: 4, Processed images: 3270
Epoch: 4, Processed images: 3280
Epoch: 4, Processed images: 3290
Epoch: 4, Processed images: 3300
Epoch: 4, Processed images: 3310
Epoch: 4, Processed images: 3320
Epoch: 4, Processed images: 3330
Epoch: 4, Processed images: 3340
Epoch: 4, Processed images: 3350
Epoch: 4, Processed images: 3360
Epoch: 4, Processed images: 3370
Epoch: 4, Processed images: 3380
Epoch: 4, Processed images: 3390
Epoch: 4, Processed images: 3400
Epoch: 4, Processed images: 3410
Epoch: 4, Processed images: 3420
Epoch: 4, Processed images: 3430
Epoch: 4, Processed images: 3440
Epoch: 4, Processed images: 3450
Epoch: 4, Processed images: 3460
Epoch: 4, Processed images: 3470
Epoch: 4, Processed images: 3480
Epoch: 4, Processed images: 3490
Epoch: 4, Processed images: 3500
Epoch: 4, Processed images: 3510
Epoch: 4, 

Epoch: 4, Processed images: 5860
Epoch: 4, Processed images: 5870
Epoch: 4, Processed images: 5880
Epoch: 4, Processed images: 5890
Epoch: 4, Processed images: 5900
Epoch: 4, Processed images: 5910
Epoch: 4, Processed images: 5920
Epoch: 4, Processed images: 5930
Epoch: 4, Processed images: 5940
Epoch: 4, Processed images: 5950
Epoch: 4, Processed images: 5960
Epoch: 4, Processed images: 5970
Epoch: 4, Processed images: 5980
Epoch: 4, Processed images: 5990
Epoch: 4, Processed images: 6000
Epoch: 4, Processed images: 6010
Epoch: 4, Processed images: 6020
Epoch: 4, Processed images: 6030
Epoch: 4, Processed images: 6040
Epoch: 4, Processed images: 6050
Epoch: 4, Processed images: 6060
Epoch: 4, Processed images: 6070
Epoch: 4, Processed images: 6080
Epoch: 4, Processed images: 6090
Epoch: 4, Processed images: 6100
Epoch: 4, Processed images: 6110
Epoch: 4, Processed images: 6120
Epoch: 4, Processed images: 6130
Epoch: 4, Processed images: 6140
Epoch: 4, Processed images: 6150
Epoch: 4, 

Epoch: 4, Processed images: 8490
Epoch: 4, Processed images: 8500
Epoch: 4, Processed images: 8510
Epoch: 4, Processed images: 8520
Epoch: 4, Processed images: 8530
Epoch: 4, Processed images: 8540
Epoch: 4, Processed images: 8550
Epoch: 4, Processed images: 8560
Epoch: 4, Processed images: 8570
Epoch: 4, Processed images: 8580
Epoch: 4, Processed images: 8590
Epoch: 4, Processed images: 8600
Epoch: 4, Processed images: 8610
Epoch: 4, Processed images: 8620
Epoch: 4, Processed images: 8630
Epoch: 4, Processed images: 8640
Epoch: 4, Processed images: 8650
Epoch: 4, Processed images: 8660
Epoch: 4, Processed images: 8670
Epoch: 4, Processed images: 8680
Epoch: 4, Processed images: 8690
Epoch: 4, Processed images: 8700
Epoch: 4, Processed images: 8710
Epoch: 4, Processed images: 8720
Epoch: 4, Processed images: 8730
Epoch: 4, Processed images: 8740
Epoch: 4, Processed images: 8750
Epoch: 4, Processed images: 8760
Epoch: 4, Processed images: 8770
Epoch: 4, Processed images: 8780
Epoch: 4, 

Epoch: 4, Processed images: 11130
Epoch: 4, Processed images: 11140
Epoch: 4, Processed images: 11150
Epoch: 4, Processed images: 11160
Epoch: 4, Processed images: 11170
Epoch: 4, Processed images: 11180
Epoch: 4, Processed images: 11190
Epoch: 4, Processed images: 11200
Epoch: 4, Processed images: 11210
Epoch: 4, Processed images: 11220
Epoch: 4, Processed images: 11230
Epoch: 4, Processed images: 11240
Epoch: 4, Processed images: 11250
Epoch: 4, Processed images: 11260
Epoch: 4, Processed images: 11270
Epoch: 4, Processed images: 11280
Epoch: 4, Processed images: 11290
Epoch: 4, Processed images: 11300
Epoch: 4, Processed images: 11310
Epoch: 4, Processed images: 11320
Epoch: 4, Processed images: 11330
Epoch: 4, Processed images: 11340
Epoch: 4, Processed images: 11350
Epoch: 4, Processed images: 11360
Epoch: 4, Processed images: 11370
Epoch: 4, Processed images: 11380
Epoch: 4, Processed images: 11390
Epoch: 4, Processed images: 11400
Epoch: 4, Processed images: 11410
Epoch: 4, Proc

Epoch: 4, Processed images: 13770
Epoch: 4, Processed images: 13780
Epoch: 4, Processed images: 13790
Epoch: 4, Processed images: 13800
Epoch: 4, Processed images: 13810
Epoch: 4, Processed images: 13820
Epoch: 4, Processed images: 13830
Epoch: 4, Processed images: 13840
Epoch: 4, Processed images: 13850
Epoch: 4, Processed images: 13860
Epoch: 4, Processed images: 13870
Epoch: 4, Processed images: 13880
Epoch: 4, Processed images: 13890
Epoch: 4, Processed images: 13900
Epoch: 4, Processed images: 13910
Epoch: 4, Processed images: 13920
Epoch: 4, Processed images: 13930
Epoch: 4, Processed images: 13940
Epoch: 4, Processed images: 13950
Epoch: 4, Processed images: 13960
Epoch: 4, Processed images: 13970
Epoch: 4, Processed images: 13980
Epoch: 4, Processed images: 13990
Epoch: 4, Processed images: 14000
Epoch: 4, Processed images: 14010
Epoch: 4, Processed images: 14020
Epoch: 4, Processed images: 14030
Epoch: 4, Processed images: 14040
Epoch: 4, Processed images: 14050
Epoch: 4, Proc

Epoch: 4, Processed images: 16300
Epoch: 4, Processed images: 16310
Epoch: 4, Processed images: 16320
Epoch: 4, Processed images: 16330
Epoch: 4, Processed images: 16340
Epoch: 4, Processed images: 16350
Epoch: 4, Processed images: 16360
Epoch: 4, Processed images: 16370
Epoch: 4, Processed images: 16380
Epoch: 4, Processed images: 16390
Epoch: 4, Processed images: 16400
Epoch: 4, Processed images: 16410
Epoch: 4, Processed images: 16420
Epoch: 4, Processed images: 16430
Epoch: 4, Processed images: 16440
Epoch: 4, Processed images: 16450
Epoch: 4, Processed images: 16460
Epoch: 4, Processed images: 16470
Epoch: 4, Processed images: 16480
Epoch: 4, Processed images: 16490
Epoch: 4, Processed images: 16500
Epoch: 4, Processed images: 16510
Epoch: 4, Processed images: 16520
Epoch: 4, Processed images: 16530
Epoch: 4, Processed images: 16540
Epoch: 4, Processed images: 16550
Epoch: 4, Processed images: 16560
Epoch: 4, Processed images: 16570
Epoch: 4, Processed images: 16580
Epoch: 4, Proc

Epoch: 4, Processed images: 19020
Epoch: 4, Processed images: 19030
Epoch: 4, Processed images: 19040
Epoch: 4, Processed images: 19050
Epoch: 4, Processed images: 19060
Epoch: 4, Processed images: 19070
Epoch: 4, Processed images: 19080
Epoch: 4, Processed images: 19090
Epoch: 4, Processed images: 19100
Epoch: 4, Processed images: 19110
Epoch: 4, Processed images: 19120
Epoch: 4, Processed images: 19130
Epoch: 4, Processed images: 19140
Epoch: 4, Processed images: 19150
Epoch: 4, Processed images: 19160
Epoch: 4, Processed images: 19170
Epoch: 4, Processed images: 19180
Epoch: 4, Processed images: 19190
Epoch: 4, Processed images: 19200
Epoch: 4, Processed images: 19210
Epoch: 4, Processed images: 19220
Epoch: 4, Processed images: 19230
Epoch: 4, Processed images: 19240
Epoch: 4, Processed images: 19250
Epoch: 4, Processed images: 19260
Epoch: 4, Processed images: 19270
Epoch: 4, Processed images: 19280
Epoch: 4, Processed images: 19290
Epoch: 4, Processed images: 19300
Epoch: 4, Proc

Epoch: 4, Processed images: 21700
Epoch: 4, Processed images: 21710
Epoch: 4, Processed images: 21720
Epoch: 4, Processed images: 21730
Epoch: 4, Processed images: 21740
Epoch: 4, Processed images: 21750
Epoch: 4, Processed images: 21760
Epoch: 4, Processed images: 21770
Epoch: 4, Processed images: 21780
Epoch: 4, Processed images: 21790
Epoch: 4, Processed images: 21800
Epoch: 4, Processed images: 21810
Epoch: 4, Processed images: 21820
Epoch: 4, Processed images: 21830
Epoch: 4, Processed images: 21840
Epoch: 4, Processed images: 21850
Epoch: 4, Processed images: 21860
Epoch: 4, Processed images: 21870
Epoch: 4, Processed images: 21880
Epoch: 4, Processed images: 21890
Epoch: 4, Processed images: 21900
Epoch: 4, Processed images: 21910
Epoch: 4, Processed images: 21920
Epoch: 4, Processed images: 21930
Epoch: 4, Processed images: 21940
Epoch: 4, Processed images: 21950
Epoch: 4, Processed images: 21960
Epoch: 4, Processed images: 21970
Epoch: 4, Processed images: 21980
Epoch: 4, Proc

Epoch: 4, Processed images: 24250
Epoch: 4, Processed images: 24260
Epoch: 4, Processed images: 24270
Epoch: 4, Processed images: 24280
Epoch: 4, Processed images: 24290
Epoch: 4, Processed images: 24300
Epoch: 4, Processed images: 24310
Epoch: 4, Processed images: 24320
Epoch: 4, Processed images: 24330
Epoch: 4, Processed images: 24340
Epoch: 4, Processed images: 24350
Epoch: 4, Processed images: 24360
Epoch: 4, Processed images: 24370
Epoch: 4, Processed images: 24380
Epoch: 4, Processed images: 24390
Epoch: 4, Processed images: 24400
Epoch: 4, Processed images: 24410
Epoch: 4, Processed images: 24420
Epoch: 4, Processed images: 24430
Epoch: 4, Processed images: 24440
Epoch: 4, Processed images: 24450
Epoch: 4, Processed images: 24460
Epoch: 4, Processed images: 24470
Epoch: 4, Processed images: 24480
Epoch: 4, Processed images: 24490
Epoch: 4, Processed images: 24500
Epoch: 4, Processed images: 24510
Epoch: 4, Processed images: 24520
Epoch: 4, Processed images: 24530
Epoch: 4, Proc

Epoch: 4, Processed images: 26750
Epoch: 4, Processed images: 26760
Epoch: 4, Processed images: 26770
Epoch: 4, Processed images: 26780
Epoch: 4, Processed images: 26790
Epoch: 4, Processed images: 26800
Epoch: 4, Processed images: 26810
Epoch: 4, Processed images: 26820
Epoch: 4, Processed images: 26830
Epoch: 4, Processed images: 26840
Epoch: 4, Processed images: 26850
Epoch: 4, Processed images: 26860
Epoch: 4, Processed images: 26870
Epoch: 4, Processed images: 26880
Epoch: 4, Processed images: 26890
Epoch: 4, Processed images: 26900
Epoch: 4, Processed images: 26910
Epoch: 4, Processed images: 26920
Epoch: 4, Processed images: 26930
Epoch: 4, Processed images: 26940
Epoch: 4, Processed images: 26950
Epoch: 4, Processed images: 26960
Epoch: 4, Processed images: 26970
Epoch: 4, Processed images: 26980
Epoch: 4, Processed images: 26990
Epoch: 4, Processed images: 27000
Epoch: 4, Processed images: 27010
Epoch: 4, Processed images: 27020
Epoch: 4, Processed images: 27030
Epoch: 4, Proc

Epoch: 4, Processed images: 29170
Epoch: 4, Processed images: 29180
Epoch: 4, Processed images: 29190
Epoch: 4, Processed images: 29200
Epoch: 4, Processed images: 29210
Epoch: 4, Processed images: 29220
Epoch: 4, Processed images: 29230
Epoch: 4, Processed images: 29240
Epoch: 4, Processed images: 29250
Epoch: 4, Processed images: 29260
Epoch: 4, Processed images: 29270
Epoch: 4, Processed images: 29280
Epoch: 4, Processed images: 29290
Epoch: 4, Processed images: 29300
Epoch: 4, Processed images: 29310
Epoch: 4, Processed images: 29320
Epoch: 4, Processed images: 29330
Epoch: 4, Processed images: 29340
Epoch: 4, Processed images: 29350
Epoch: 4, Processed images: 29360
Epoch: 4, Processed images: 29370
Epoch: 4, Processed images: 29380
Epoch: 4, Processed images: 29390
Epoch: 4, Processed images: 29400
Epoch: 4, Processed images: 29410
Epoch: 4, Processed images: 29420
Epoch: 4, Processed images: 29430
Epoch: 4, Processed images: 29440
Epoch: 4, Processed images: 29450
Epoch: 4, Proc

Epoch: 4, Processed images: 31940
Epoch: 4, Processed images: 31950
Epoch: 4, Processed images: 31960
Epoch: 4, Processed images: 31970
Epoch: 4, Processed images: 31980
Epoch: 4, Processed images: 31990
Epoch: 4, Processed images: 32000
Epoch: 4, Processed images: 32010
Epoch: 4, Processed images: 32020
Epoch: 4, Processed images: 32030
Epoch: 4, Processed images: 32040
Epoch: 4, Processed images: 32050
Epoch: 4, Processed images: 32060
Epoch: 4, Processed images: 32070
Epoch: 4, Processed images: 32080
Epoch: 4, Processed images: 32090
Epoch: 4, Processed images: 32100
Epoch: 4, Processed images: 32110
Epoch: 4, Processed images: 32120
Epoch: 4, Processed images: 32130
Epoch: 4, Processed images: 32140
Epoch: 4, Processed images: 32150
Epoch: 4, Processed images: 32160
Epoch: 4, Processed images: 32170
Epoch: 4, Processed images: 32180
Epoch: 4, Processed images: 32190
Epoch: 4, Processed images: 32200
Epoch: 4, Processed images: 32210
Epoch: 4, Processed images: 32220
Epoch: 4, Proc

Epoch: 4, Processed images: 34440
Epoch: 4, Processed images: 34450
Epoch: 4, Processed images: 34460
Epoch: 4, Processed images: 34470
Epoch: 4, Processed images: 34480
Epoch: 4, Processed images: 34490
Epoch: 4, Processed images: 34500
Epoch: 4, Processed images: 34510
Epoch: 4, Processed images: 34520
Epoch: 4, Processed images: 34530
Epoch: 4, Processed images: 34540
Epoch: 4, Processed images: 34550
Epoch: 4, Processed images: 34560
Epoch: 4, Processed images: 34570
Epoch: 4, Processed images: 34580
Epoch: 4, Processed images: 34590
Epoch: 4, Processed images: 34600
Epoch: 4, Processed images: 34610
Epoch: 4, Processed images: 34620
Epoch: 4, Processed images: 34630
Epoch: 4, Processed images: 34640
Epoch: 4, Processed images: 34650
Epoch: 4, Processed images: 34660
Epoch: 4, Processed images: 34670
Epoch: 4, Processed images: 34680
Epoch: 4, Processed images: 34690
Epoch: 4, Processed images: 34700
Epoch: 4, Processed images: 34710
Epoch: 4, Processed images: 34720
Epoch: 4, Proc

Epoch: 4, Processed images: 37170
Epoch: 4, Processed images: 37180
Epoch: 4, Processed images: 37190
Epoch: 4, Processed images: 37200
Epoch: 4, Processed images: 37210
Epoch: 4, Processed images: 37220
Epoch: 4, Processed images: 37230
Epoch: 4, Processed images: 37240
Epoch: 4, Processed images: 37250
Epoch: 4, Processed images: 37260
Epoch: 4, Processed images: 37270
Epoch: 4, Processed images: 37280
Epoch: 4, Processed images: 37290
Epoch: 4, Processed images: 37300
Epoch: 4, Processed images: 37310
Epoch: 4, Processed images: 37320
Epoch: 4, Processed images: 37330
Epoch: 4, Processed images: 37340
Epoch: 4, Processed images: 37350
Epoch: 4, Processed images: 37360
Epoch: 4, Processed images: 37370
Epoch: 4, Processed images: 37380
Epoch: 4, Processed images: 37390
Epoch: 4, Processed images: 37400
Epoch: 4, Processed images: 37410
Epoch: 4, Processed images: 37420
Epoch: 4, Processed images: 37430
Epoch: 4, Processed images: 37440
Epoch: 4, Processed images: 37450
Epoch: 4, Proc